routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\dashboard\PostController;
use App\Http\Controllers\dashboard\UserController;
use App\Http\Controllers\dashboard\CategoryController;
use App\Http\Controllers\web\WebController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->name('home');


Route::resource('/dashboard/post', PostController::class);
Route::post('/dashboard/post/{post}/image',[PostController::class,'image'])->name('post.image');

Route::resource('/dashboard/category', CategoryController::class);
Route::resource('/dashboard/user', UserController::class);




Route::get('/', [WebController::class,'index'])->name('index');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

use App\Models\Rol;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'user',
        'rol_id',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function rol(){
        return $this->belongsTo(Rol::class);
    }
}

app/Http/Controllers/dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreCategoryPost;

class CategoryController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {

        $this->middleware(['auth','rol.admin']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories= Category::orderBy('created_at','desc')->paginate(5);
        //appserviceprovider para arrelgar la pagination en larave8
        return view("dashboard.category.index")->with('categories',$categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("dashboard.category.create",['category'=> new Category()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCategoryPost $request)
    {
        Category::create($request->validated());        
        return back()->with('status','Categoría creada con exito');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view("dashboard.category.show")->with('category',$category);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view("dashboard.category.edit")->with('category',$category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(StoreCategoryPost $request, Category $category)
    {
        $category->update($request->validated());
        return back()->with('status','Categoria actualizada con exito');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return back()->with('status','Categoría eliminada con exito');
    }
}

app/Http/Controllers/dashboard/PostController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Models\Post;
use App\Models\Category;
use App\Models\PostImage;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StorePostPost;

class PostController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(['auth','rol.admin']);
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts= Post::orderBy('created_at','desc')->paginate(5);
        //appserviceprovider para arrelgar la pagination en larave8
        return view("dashboard.post.index")->with('posts',$posts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::pluck('id','title');
        return view("dashboard.post.create",['post'=> new Post()])->with('categories',$categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePostPost $request)
    {
        
        Post::create($request->validated());
       
        return back()->with('status','Post creado con exito');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view("dashboard.post.show")->with('post',$post);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories = Category::pluck('id','title');
        return view("dashboard.post.edit")->with('post',$post)->with('categories',$categories);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StorePostPost $request, Post $post)
    {
        $post->update($request->validated());
        return back()->with('status','Post actualizado con exito');
    }

    public function image(Request $request, Post $post)
    {
        $request->validate([
            'image'=>'required|mimes:jpeg,bmp,png|max:10240' //10MB
        ]);

        $filename = time().".".$request->image->extension();

        $request->image->move(public_path('images'),$filename);

        PostImage::create(['image'=> $filename , 'post_id'=>$post->id]);
        return back()->with('status','Imagen cargada con exito');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
        return back()->with('status','Post eliminado con exito');
    }
}

app/Http/Controllers/dashboard/UserController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreUserPost;
use App\Http\Requests\UpdateUserPut;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {

        $this->middleware(['auth','rol.admin']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users= User::orderBy('created_at','desc')->paginate(5);
        //appserviceprovider para arrelgar la pagination en larave8
        return view("dashboard.user.index")->with('users',$users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("dashboard.user.create",['user'=> new User()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUserPost $request)
    {
        User::create([
            'name' => $request['name'],
            'surname' => $request['surname'],
            'rol_id' => 1, //rol regular
            'email' => $request['email'],
            'password' => Hash::make($request['password']),
        ]);        
        return back()->with('status','Usuario creado con exito');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view("dashboard.user.show")->with('user',$user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view("dashboard.user.edit")->with('user',$user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserPut $request, User $user)
    {
        $user->update([
            'name' => $request['name'],
            'surname' => $request['surname'],
            'email' => $request['email'],            
        ]);
        return back()->with('status','Usuario actualizado con exito');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return back()->with('status','Usuario eliminado con exito');
    }
}

resources/views/dashboard/user/_form.blade.php
@csrf
<div class="form-group">
    <label for="name">Nombre</label>
    <input type="text" class="form-control" name="name" id="name" value="{{ old('name',$user->name) }}">
</div>
<div class="form-group">
    <label for="surname">Apellido</label>
    <input type="text" class="form-control" name="surname" id="surname" value="{{ old('surname',$user->surname) }}">
</div>
<div class="form-group">
    <label for="email">Email</label>
    <input type="email" class="form-control" name="email" id="email" value="{{ old('email',$user->email) }}">
</div>
@if ($pasw)
<div class="form-group">
    <label for="password">Contraseña</label>
    <input type="password" class="form-control" name="password" id="emaipasswordl" value="{{ old('password',$user->password) }}">
</div> 
@endif


<input type="submit" class="btn btn-primary" value="Enviar">

resources/views/dashboard/user/create.blade.php
@extends('dashboard.post.master')

@section('content')

    @include('dashboard.partials.validation-error')
    <form action="{{ route('user.store') }}" method="POST">
        @include('dashboard.user._form',['pasw'=>true])
    </form>
@endsection

resources/views/dashboard/user/edit.blade.php
@extends('dashboard.post.master')

@section('content')

    @include('dashboard.partials.validation-error')
    <form action="{{route("user.update",$user->id)}}" method="POST">
        @method('PUT')
        @include('dashboard.user._form',['pasw'=>false])
    </form>

@endsection

resources/views/dashboard/user/index.blade.php
@extends('dashboard.post.master')

@section('content')
    <a class="btn btn-primary btn-sm mt-3 mb-3" href="{{ route('user.create') }}">
        Crear
    </a>
    <table class="table">
        <thead>
            <tr>
                <td>
                    Id
                </td>
                <td>
                    Nombre
                </td>
                <td>
                    Apellido
                </td>
                <td>
                    Email
                </td>
                <td>
                    Rol
                </td>
                <td>
                    Actualización
                </td>
                <td>
                    Edición
                </td>
                <td>
                    Acciones
                </td>
            </tr>
        </thead>
        <tbody>
            @foreach ($users as $user)
                <tr>
                    <td>
                        {{ $user->id }}
                    </td>
                    <td>
                        {{ $user->name }}
                    </td>
                    <td>
                        {{ $user->surname }}
                    </td>
                    <td>
                        {{ $user->email }}
                    </td>
                    <td>
                        {{ $user->rol->key }}
                    </td>
                    <td>
                        {{ $user->created_at->format('d-m-Y') }}
                    </td>
                    <td>
                        {{ $user->updated_at->format('d-m-Y') }}
                    </td>
                    <td>
                        <a href="{{ route('user.show', $user->id) }}" class="btn btn-primary">Ver</a>
                        <a href="{{ route('user.edit', $user->id) }}" class="btn btn-primary">Editar</a>
                        <button data-toggle="modal" data-target="#deleteModal" data-id="{{ $user->id }}"
                            class="btn btn-danger">
                            Eliminar
                        </button>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    {{ $users->links() }}

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalLabel"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>¿Seguro que desea eliminar el registro seleccionado?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>

                    <form id="formDelete" method="POST" action="{{ route('user.destroy', 0) }}"
                        data-action="{{ route('user.destroy', 0) }}">
                        @method('DELETE')
                        @csrf
                        <button type="submit" class="btn btn-danger">Borrar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        window.onload = function() {
            $('#deleteModal').on('show.bs.modal', function(event) {
                var button = $(event.relatedTarget) // Button that triggered the modal
                var id = button.data('id') // Extract info from data-* attributes
                // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
                // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
                var action = $('#formDelete').attr('data-action').slice(0, -1)
                console.log(action)
                $('#formDelete').attr('action', action + id)
                var modal = $(this)
                modal.find('.modal-title').text('Vas a borrar el usuario: ' + id)

            })
        }
    </script>
@endsection

resources/views/dashboard/user/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
    <script src="{{asset('js/app.js')}}"></script>
    <title>Modulo admin</title>
</head>
<body>
    @include('dashboard.partials.nav-header-main')
    <div class="container">
        @include('dashboard.partials.session-flash-status')
        @yield('content')
    </div>
</body>
</html>

resources/views/dashboard/user/show.blade.php
@extends('dashboard.post.master')

@section('content')

        <div class="form-group">
            <label for="name">Nombre</label>
            <input readonly type="text" class="form-control" name="name" id="name" value="{{$user->name}}">
        </div>
        <div class="form-group">
            <label for="surname">Apellido</label>
            <input readonly type="text" class="form-control" name="surname" id="surname" value="{{$user->surname}}">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input readonly type="text" class="form-control" name="email" id="email" value="{{$user->email}}">
        </div>
        
@endsection